### ISSUE TITLE
undefined method `value_before_type_cast' in Rails 4.2

### ISSUE THREAD

**Issue by rvfx** [JackDanger/permanent_records#40]
I just updated Rails from 4.1.8 to 4.2. When I `.destroy` an entry, I get this error:
```
undefined method `value_before_type_cast' for 1000:Fixnum
```
where `1000` is the ID of my entry.
I only get this error when the permanent_records gem is in use.

The backtrace:
```
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/before_type_cast.rb:46:in `read_attribute_before_type_cast'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:155:in `block in original_raw_attribute'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:154:in `original_raw_attribute'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:73:in `attribute_changed_in_place?'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:149:in `block in changed_in_place'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:148:in `changed_in_place'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:141:in `attributes_changed_in_place'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:62:in `changed_attributes'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/associations/builder/belongs_to.rb:66:in `touch_record'
gems/ruby-2.1.2/gems/activerecord-4.2.0/lib/active_record/associations/builder/belongs_to.rb:103:in `block in add_touch_callbacks'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_destroy_callbacks'
gems/ruby-2.1.2/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
gems/ruby-2.1.2/bundler/gems/permanent_records-ea027de935e7/lib/permanent_records.rb:80:in `destroy_with_permanent_records'
gems/ruby-2.1.2/bundler/gems/permanent_records-ea027de935e7/lib/permanent_records.rb:40:in `destroy'
app/controllers/entries_controller.rb:112:in `destroy'
```

**Comment by rvfx** [comment]
https://github.com/JackDanger/permanent_records/tree/rails-4-2 fixes this. Thanks!

**Comment by mherold** [comment]
Ok nice! Thanks for testing!
